function apply_plot_style(ax)
%APPLY_PLOT_STYLE Shared publication-style axes formatting.
if nargin < 1 || isempty(ax)
    ax = gca;
end
grid(ax, 'on');
box(ax, 'on');
set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 0.9, ...
    'GridLineStyle', '-', ...
    'GridAlpha', 0.22, ...
    'MinorGridAlpha', 0.12, ...
    'Layer', 'top', ...
    'TickDir', 'in');
xlabel(ax, ax.XLabel.String, 'Interpreter', 'latex', 'FontName', 'Times New Roman', 'FontSize', 11);
ylabel(ax, ax.YLabel.String, 'Interpreter', 'latex', 'FontName', 'Times New Roman', 'FontSize', 11);
end
