function fig = create_paper_figure()
%CREATE_PAPER_FIGURE Create a compact figure canvas for paper-style plots.
fig = figure('Color', 'w', ...
    'Units', 'inches', ...
    'Position', [1, 1, 7.0, 5.0], ...
    'PaperPositionMode', 'auto');
end
