function format_paper_legend(lgd)
%FORMAT_PAPER_LEGEND Apply a consistent publication-style legend format.
set(lgd, ...
    'Box', 'on', ...
    'Color', 'white', ...
    'EdgeColor', 'black', ...
    'LineWidth', 0.8, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9);
end
